# utils/report_generator.py
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
import datetime

def generate_report(target_url, findings, filename="report.pdf"):
    doc = SimpleDocTemplate(filename, pagesize=A4)
    styles = getSampleStyleSheet()
    elements = []

    # Title
    elements.append(Paragraph("<b>Web Vulnerability Scan Report</b>", styles["Title"]))
    elements.append(Spacer(1, 12))

    # Metadata
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    elements.append(Paragraph(f"<b>Target URL:</b> {target_url}", styles["Normal"]))
    elements.append(Paragraph(f"<b>Scan Date:</b> {now}", styles["Normal"]))
    elements.append(Spacer(1, 12))

    # Summary
    elements.append(Paragraph("<b>Summary of Findings</b>", styles["Heading2"]))
    elements.append(Spacer(1, 8))

    data = [["Vulnerability", "Type", "Severity", "Confidence", "Evidence", "Payload", "URL"]]
    for f in findings:
        data.append([
            f.get("vulnerability", ""),
            f.get("type", ""),
            f.get("severity", ""),
            f"{f.get('confidence', '')}%",
            (f.get("evidence") or "")[:200],   # limit length
            f.get("payload", ""),
            f.get("url", "")
        ])

    table = Table(data, repeatRows=1, hAlign="LEFT", colWidths=[90, 60, 50, 60, 150, 80, 120])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#4F81BD")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("ALIGN", (0, 0), (-1, -1), "LEFT"),
        ("GRID", (0, 0), (-1, -1), 0.25, colors.grey),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("BACKGROUND", (0, 1), (-1, -1), colors.whitesmoke),
    ]))

    elements.append(table)
    elements.append(Spacer(1, 20))
    elements.append(Paragraph(
        "This report was automatically generated by the Web Vulnerability Scanner. "
        "All findings should be manually verified before taking action.",
        styles["Italic"]
    ))

    doc.build(elements)
